language: java
jdk: oraclejdk8
sudo: false
notifications:
    slack: javasneps-2018:VO13VcwbL6X6e2COPNU0AOnW
coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null
script:
  - ant compile test-compile test
after_success:
  - bash <(curl -s https://codecov.io/bash)
